version: '3.8'

services:
  flight_service:
    build: ./flight_service
    ports:
      - "8081:8081"
    networks:
      - backend

  hotel_services:
    build: ./hotel_services
    ports:
      - "8082:8082"
    networks:
      - backend

  payment_service:
    build: ./payment_service
    ports:
      - "8083:8083"
    networks:
      - backend

  booking_service:
    build: ./booking_service
    ports:
      - "8084:8084"
    depends_on:
      - flight_service
      - hotel_services
      - payment_service
    networks:
      - backend

networks:
  backend:
